package org.act.cat;

import java.util.List;

/**
 * An effectively immutable container for output data generated by the
 * {@link CatEngine}.
 */
public interface CatOutput {
    /**
     * Returns the indicator of whether the test is complete or not.
     *
     * @return true if the test is complete, false otherwise
     */
    boolean getTestComplete();

    /**
     * Gets an ordered list of the item item identifiers of the next items in
     * the shadow test.
     *
     * @return an ordered list of the item item identifiers of the next items in
     *         the shadow test, or an empty list if the test is complete.
     */
    CatItemsToAdminister getItemsToAdminister();

    /**
     * Returns the value of the ability estimate.
     *
     * @return the ability estimate {@code ThetaEst}
     */
    ThetaEst getThetaEst();

    PassageOrItemEligibilityAtThetaRange getPassageOrItemEligibilityAtThetaRange();

    List<String> getShadowTest();

    double getCatEngineTime();

    double getSolverTime();

}
